title: "Salud Integral"
description: "Blog para la salud holística"
baseurl: ""
url: "https://salud-integral.www-haosp.org"

# Tema seguro para GitHub Pages
remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Autor
author:
  name: "Héctor Augusto Ospina Angarita"
  email: "haospina14@hotmail.com"

# Build
markdown: kramdown
highlighter: rouge
permalink: pretty
